[package]
name = "dispersed-iterators"
version = "0.1.0"
edition = "2021"
authors = ["DasLixou"]
description = "Dispersed Iterators for Rust"
repository = "https://github.com/DasLixou/dispersed-iterators"
license = "MIT OR Apache-2.0"
readme = "README.md"
exclude = ["examples"]

[dependencies]
